### ISSUE TITLE
Medusa 1.18.1 - Undefined plugin

### ISSUE THREAD

**Issue by iamanle** [adrien2p/medusa-plugins#125]
Env:
- Node 18.16.1
- "medusa-plugin-auth": "^1.8.3",
- "@medusajs/medusa": "1.18.1",

Config setup:
As usual for firebase

```
 {
    resolve: 'medusa-plugin-auth',
    options: {
      firebase: {
        credentialJsonPath: 'credentials/goloco-715d5-firebase-adminsdk-z7gkn-22da47ded5.json',
        admin: {
          // authPath: '/admin/auth/firebase',
          expiresIn: ONE_MONTH,
        },
        store: {
          // authPath: '/store/auth/firebase',
          expiresIn: ONE_MONTH,
          verifyCallback: async (container, decodedToken) => {
            const email = decodedToken.email;
            const firebaseId = decodedToken.uid;
            const manager = container.resolve('manager');
            const customerService = container.resolve('customerService');
```

Error:
When `yarn build`:

```
➜ yarn build  
yarn run v1.22.19
warning package.json: "dependencies" has dependency "babel-preset-medusa-package" with range "^1.1.13" that collides with a dependency in "devDependencies" of the same name with version "^1.1.19"
$ cross-env npm run clean && npm run build:server && npm run build:admin

> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist


> medusa-starter-default@0.0.1 build:server
> cross-env npm run clean && tsc -p tsconfig.server.json


> medusa-starter-default@0.0.1 clean
> cross-env ./node_modules/.bin/rimraf dist


> medusa-starter-default@0.0.1 build:admin
> cross-env medusa-admin build

TypeError: Cannot read properties of undefined (reading 'plugins')
    at loadConfig (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/utils/load-config.js:8:31)
    at Command.<anonymous> (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:50:49)
    at step (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:33:23)
    at Object.next (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:14:53)
    at /Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:4:12)
    at Command.build (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/@medusajs/admin/commands/build.js:45:12)
    at Command.listener [as _actionHandler] (/Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/commander/lib/command.js:482:17)
    at /Users/anle/Desktop/flip/flip-ticketing-v1/node_modules/commander/lib/command.js:1283:65
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gempain** [comment]
I do have the same issue though. It's happening with the auth plugin only.

**Comment by gempain** [comment]
Alright, so, I added some logging in `/my-store/node_modules/@medusajs/admin/utils/load-config.js` and interesting find right there which explains everything:

```
var configModule = (0, medusa_core_utils_1.getConfigFile)(process.cwd(), "medusa-config").configModule;
console.log('configModule', (0, medusa_core_utils_1.getConfigFile)(process.cwd(), "medusa-config"));
```

Gives me this log:

```
> medusa-starter-default@0.0.1 build:admin
> cross-env medusa-admin build

configModule {
  configModule: undefined,
  configFilePath: '/my-store/medusa-config.js',
  error: ReferenceError: BACKEND_URL is not defined
      at Object.<anonymous> (/my-store/medusa-config.js:63:29)
```

I guess:
- plugins should be able to validate their options and throw an error when the options are invalid
- when medusa isn't valid, it should throw an error, to avoid things going further
