### ISSUE TITLE
An error occurred while registering endpoints in medusa-plugin-auth TypeError: app.use() requires a middleware function

### ISSUE THREAD

**Issue by luluhoc** [adrien2p/medusa-plugins#129]
I'm getting this error i'm using medusa 1.19

```
warn:    An error occurred while registering endpoints in medusa-plugin-auth
warn:    TypeError: app.use() requires a middleware function
    at Function.use (/Users/lucjangrzesik/Desktop/retrobroker/server/node_modules/express/lib/application.js:217:11)
    at /Users/lucjangrzesik/Desktop/retrobroker/server/node_modules/@medusajs/medusa/dist/loaders/plugins.js:436:37
    at step (/Users/lucjangrzesik/Desktop/retrobroker/server/node_modules/@medusajs/medusa/dist/loaders/plugins.js:56:23)
    at Object.next (/Users/lucjangrzesik/Desktop/retrobroker/server/node_modules/@medusajs/medusa/dist/loaders/plugins.js:37:53)
⠹ Initializing plugins
```

my config

```
{
    resolve: "medusa-plugin-auth",
    /** @type {import('medusa-plugin-auth').AuthOptions} */
    options: {
      // strict: "all", // or "none" or "store" or "admin"
      google: {
        clientID: GoogleClientId,
        clientSecret: GoogleClientSecret,

        admin: {
          callbackUrl: `${BACKEND_URL}/admin/auth/google/cb`,
          failureRedirect: `${ADMIN_URL}/login`,

          // The success redirect can be overriden from the client by adding a query param `?redirectTo=your_url` to the auth url
          // This query param will have the priority over this configuration
          successRedirect: `${ADMIN_URL}/`,

          authPath: '/admin/auth/google',
          // authCallbackPath: '/admin/auth/google/cb',
          // expiresIn: 24 * 60 * 60 * 1000,
          // verifyCallback: (container, req, accessToken, refreshToken, profile, strict) => {
          //    // implement your custom verify callback here if you need it
          // }
        },

        store: {
          callbackUrl: `${BACKEND_URL}/store/auth/google/cb`,
          failureRedirect: `${STORE_URL}/login`,

          // The success redirect can be overriden from the client by adding a query param `?redirectTo=your_url` to the auth url
          // This query param will have the priority over this configuration
          successRedirect: `${STORE_URL}/`,

          authPath: '/store/auth/google',
          authCallbackPath: '/store/auth/google/cb',
          // expiresIn: 24 * 60 * 60 * 1000,
          // verifyCallback: (container, req, accessToken, refreshToken, profile, strict) => {
          //     console.log('verifyCallback')
          //     console.log(profile)
          //     console.log(accessToken)
          //     console.log(refreshToken)

          //    // implement your custom verify callback here if you need it
          // }
        }
      }
    }
  },
```

**Comment by luluhoc** [comment]
@adrien2p

**Comment by adrien2p** [comment]
I suggest you to look at this one https://discord.com/channels/876835651130097704/1192132522285469715 i ve already provided a solution 😊

**Comment by luluhoc** [comment]
> I suggest you to look at this one https://discord.com/channels/876835651130097704/1192132522285469715 i ve already provided a solution 😊

oh, thanks it's working now

**Comment by aldo-roman** [comment]
@adrien2p I cannot see the link. It somehow doesn't load. Could you please share the solution here?

**Comment by aldo-roman** [comment]
Somehow the discord link won't open for me. Thanks for sharing here. I guess it's better here, too.
