### ISSUE TITLE
medusa-plugin-auth plugin not working with latest version of medusa.

### ISSUE THREAD

**Issue by the-special-character** [adrien2p/medusa-plugins#131]
Unable to use medusa-plugin-auth getting following error while using it.

warn:    An error occurred while registering endpoints in medusa-plugin-auth
warn:    TypeError: app.use() requires a middleware function
    at Function.use (/Users/yag/Documents/projects/my-medusa-store/node_modules/express/lib/application.js:217:11)
    at /Users/yag/Documents/projects/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:376:37
    at step (/Users/yag/Documents/projects/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/Users/yag/Documents/projects/my-medusa-store/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)

**Comment by adrien2p** [comment]
Would have been nice to look for existing issues first 😊

https://github.com/adrien2p/medusa-plugins/issues/129
