### ISSUE TITLE
Auth with Google: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by OmarMHawash** [adrien2p/medusa-plugins#164]
Hi, I've sterted a help [new thread](https://discord.com/channels/876835651130097704/1244990602148581457) on discord channel, and also posting here. I've followed the documentation to add **Google authentication** for my store, and also went through a [similar thread](https://discord.com/channels/876835651130097704/1205582972653142056), but still facing this issue in my medusa store:

When I hit continue from the _google login screen_ it gets stuck loading or redirecting to the app, and my medusa backend shows this error about the **id** of the req.user object in `authenticateSessionFactory` function:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/auth-callback-middleware.js:36:44
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/passport/utils/auth-routes-builder.js:89:9
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/passport/utils/auth-routes-builder.js:46:98
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/auth-callback-middleware.js:15:9
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/passport/utils/auth-routes-builder.js:70:20
    at strategy.error (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport/lib/middleware/authenticate.js:361:18)
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/lib/strategy.js:177:34
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:196:18
    at passBackControl (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:132:9)
    ...
```

I've tried to log the req.user : authenticateSessionFactory return ~ req.user: undefined
Alternately, I've tried to setup **Facebook login** and it worked.

**Versions**
medusa : 1.20.6 (latest)
medusa-plugin-auth: 1.10.4 (latest)

**Comment by adrien2p** [comment]
Hi, could you share you plugin config please

**Comment by OmarMHawash** [comment]
> Hi, could you share you plugin config please

It's just the default config, straight from the documentation.

**Comment by adrien2p** [comment]
that is pretty strange, does it work for the admin?

**Comment by adrien2p** [comment]
would you mind putting some logs [here](https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-auth/src/core/passport/utils/auth-routes-builder.ts#L105) please?

**Comment by OmarMHawash** [comment]
> would you mind putting some logs [here](https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-auth/src/core/passport/utils/auth-routes-builder.ts#L105) please?

```
router.get ~ err: TokenError: client_secret is missing.
    at OAuth2Strategy.parseErrorResponse (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:196:18
    at passBackControl (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/omarmhawash/Desktop/projects/medusa-store/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'invalid_request',
  uri: undefined,
  status: 500
}
router.get ~ user: undefined
router.get ~ options: undefined
authenticateSessionFactory return ~ req.user: undefined
TypeError: Cannot read properties of undefined (reading 'id')
    at /Users/omarmhawash/Desktop/projects/medusa-store/node_modules/medusa-plugin-auth/core/auth-callback-middleware.js:36:44
```

I see here that client secret is missing, but its there:
<img width="869" alt="Screen Shot 2024-05-30 at 2 36 18 PM" src="https://github.com/adrien2p/medusa-plugins/assets/81506354/9f4f01b2-a410-4d47-9938-456db4c18638">

**Comment by adrien2p** [comment]
Would you be able to log it maybe to validate that it is there and goes through? You should see it in the constructor here https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-auth/src/auth-strategies/google/store.ts

**Comment by OmarMHawash** [comment]
> Would you be able to log it maybe to validate that it is there and goes through? You should see it in the constructor here https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-auth/src/auth-strategies/google/store.ts

It's not, clientID is there, but clientSecret isn't reaching the constructor... 
Strange, what might be the case?

```
constructor ~ strategyOptions: {
  type: 'google',
  strict: 'none',
  identifier: 'google',
  clientID: 'there_is_a_client_id',
  clientSecret: '',
  admin: {
    callbackUrl: 'http://localhost:9000/admin/auth/google/cb',
    failureRedirect: 'http://localhost:7001/login',
    successRedirect: 'http://localhost:7001/'
  },
  store: {
    callbackUrl: 'http://localhost:9000/store/auth/google/cb',
    failureRedirect: 'http://localhost:8000/login',
    successRedirect: 'http://localhost:8000/'
  }
}
```

**Comment by adrien2p** [comment]
could you log the client secret from your medusa-config just to be absolutely sure :)

**Comment by OmarMHawash** [comment]
> could you log the client secret from your medusa-config just to be absolutely sure :)

😅 I feel so Bad, It's mis-spelled
<img width="233" alt="Screen Shot 2024-05-30 at 6 32 18 PM" src="https://github.com/adrien2p/medusa-plugins/assets/81506354/29ba2687-296b-4cab-9159-715241816f96">
