### ISSUE TITLE
Unknown authentication strategy "azure-oidc.admin.medusa-auth-plugin_azure_oidc"

### ISSUE THREAD

**Issue by nickmza** [adrien2p/medusa-plugins#182]
I am following this guide to enable authentication via Azure OIDC: https://medusa-plugins.vercel.app/authentication/azureoidc

I have added the following dependencies:
"medusa-plugin-auth": "^1.11.1",
    "passport": "^0.6.0",
    "passport-azure-ad": "^4.3.5",

When I hit the following route: http://localhost:9000/admin/auth/azure

I receive this error:
Error: Unknown authentication strategy "azure-oidc.admin.medusa-auth-plugin_azure_oidc"
    at attempt (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/route.js:149:13)
    at /Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/core/passport/utils/auth-routes-builder.js:40:9
    at Layer.handle [as handle_request] (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nicmck/dev/hr/medusa/mcb-store/node_modules/medusa-plugin-auth/node_modules/express/lib/router/index.js:284:15

I have stepped through the code and the strategy is not being loaded in the passport module. I can see that that the Azure admin routers are loaded and that the Azure strategy class is loaded as well. 

Any ideas on what else I can try?

**Comment by adrien2p** [comment]
In general it can be that there is two different versions of passport in your node modules
