### ISSUE TITLE
Error: Medusa Sentry Integration Throwing error

### ISSUE THREAD

**Issue by sats268842** [adrien2p/medusa-plugins#53]
Plugin sentry was added. When I first tried to run it, it failed.

Error Message:

D:\medusa-framework-server-api\medusa-config.js:71
          new Sentry.Integrations.Http({ tracing: true })
                     ^

TypeError: Cannot read properties of undefined (reading 'Integrations')
    at Object.integrations (D:\medusa-framework-server-api\medusa-config.js:71:22)
    at resolveConfigProperties (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\core\utils.js:87:42)
    at resolveConfigProperties (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\core\utils.js:84:23)
    at resolveConfigProperties (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\core\utils.js:84:23)
    at resolveConfigProperties (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\core\utils.js:84:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async asyncLoadConfig (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\core\utils.js:92:26)
    at async Medusa.load (D:\medusa-framework-server-api\node_modules\medusa-extender\dist\Medusa.js:40:30)
    at async bootstrap (D:\medusa-framework-server-api\dist\main.js:11:5)

Node.js v18.12.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by adrien2p** [comment]
I assume that you are using the extender, is that right? In that case could you update to the latest version please

**Comment by sats268842** [comment]
Thank you, it works.
