### ISSUE TITLE
Google OAuth is not working for existing user(created using email/password-flow) try to login

### ISSUE THREAD

**Issue by sats268842** [adrien2p/medusa-plugins#77]
Error:
"GET /store/auth/google/cb?code=*********************************&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=none HTTP/1.1" 500 148 "-" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36"
TokenError: Bad Request
    at OAuth2Strategy.parseErrorResponse (/app/medusa/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/app/medusa/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /app/medusa/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /app/medusa/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/app/medusa/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/app/medusa/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:523:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
$ ^C
$ ^C

**Comment by adrien2p** [comment]
If the user already exists, it is a security issue if he could just logged in with another logging type. Let's imagine someone hacked your email account, he could just log in into all your plateformes even if it wasn't the original register method. Now if you want to authorised it, you can update the metadata with the auth provider

**Comment by sats268842** [comment]
My problem is that it throws an api error instead than redirecting to the storefront url site if a user already exists.
